# Autogenerated by nbdev

d = { 'settings': { 'branch': '{branch}',
                'doc_baseurl': '/{test}/',
                'doc_host': 'https://{user}.github.io',
                'git_url': 'https://github.com/{user}/{repo}/',
                'lib_path': '{test}'},
  'syms': { '{test}.core': {'{test}.core.foo': ('core.html#foo', '{test}/core.py')},
            '{test}.test_file': {'{test}.test_file.foo': ('core.html#foo', '{test}/test_file.py')}}}
