# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_everything.ipynb.

# %% ../01_everything.ipynb 3
from __future__ import print_function

# %% ../01_everything.ipynb 4
from __future__ import absolute_import
from fastcore.utils import patch,patch_to

# %% auto 0
__all__ = ['m_y', 'n_y', 'q_y', 'a_y', 'b_y', 'd_y', 'e_y', 'o_y', 'p_y']

# %% ../01_everything.ipynb 8
def a_y(): ...

# %% ../01_everything.ipynb 9
def a_y(f): # should only appear once
    def ai_n(): ...
    class a2i_n(): ...
    return f

# %% ../01_everything.ipynb 10
def b_y(a:bool)->int: ...

# %% ../01_everything.ipynb 11
#just another comment
def c_y_nall(): ...

# %% ../01_everything.ipynb 12
class d_y():
    def di_n(): ...
    class d2i_n(): ...

@a_y
async def e_y(): ...

# %% ../01_everything.ipynb 13
@patch
def d3i_n(self:d_y): ...

# %% ../01_everything.ipynb 14
@patch_to(d_y)
def d4i_n(self): ...

# %% ../01_everything.ipynb 15
def _f_y_nall(): ...

# %% ../01_everything.ipynb 21
m_y = n_y = 1

# %% ../01_everything.ipynb 22
exec("o_y=1")
exec("p_y=1")
_all_ = [o_y, 'p_y']

# %% ../01_everything.ipynb 23
q_y,_r_n = (1,1)

# %% ../01_everything.ipynb 24
a_y.test = 1
